import {
  Beer,
  Coffee,
  Fish,
  GlassWater,
  IceCreamBowl,
  Pizza,
  Soup,
  Sparkles,
  Utensils,
  Wine,
  X
} from "lucide-react";

export const translations = {
  en: {
    nav: ["Menu", "Delivery", "Restaurant"],
    popular: "Popular",
    food: "Food",
    drinks: "Drinks",
    search: "Search dishes, ingredients or drinks...",
    all: "All",
    filters: ["All", "Popular", "Vegetarian", "Spicy", "Under $20"],
    infoTitle: "Restaurant information",
    open: "Open today",
    address: "Address",
    phone: "Phone",
    delivery: "Delivery",
    pickup: "Pickup",
    dinein: "Dine in",
    eta: "25–40 min",
    minOrder: "Minimum order",
    freeDelivery: "Free delivery over $45",
    favorites: "Favorites",
    cart: "Cart",
    emptyFavorites: "You have no favorite items yet.",
    emptyCart: "Your cart is empty.",
    add: "Add",
    added: "Added to cart",
    remove: "Remove",
    subtotal: "Subtotal",
    fee: "Delivery fee",
    total: "Total",
    checkout: "Checkout",
    orderTitle: "Order details",
    customerName: "Full name",
    customerPhone: "Phone number",
    customerEmail: "Email",
    orderType: "Order type",
    deliveryAddress: "Street and building",
    apartment: "Apartment / intercom",
    city: "City",
    postalCode: "Postal code",
    deliveryNotes: "Delivery notes",
    payment: "Payment method",
    card: "Card",
    cash: "Cash",
    placeOrder: "Place demo order",
    orderSuccess: "Order placed successfully",
    quantity: "Quantity",
    details: "Details",
    ingredients: "Ingredients",
    allergens: "Allergens",
    preparation: "Preparation",
    calories: "Calories",
    seasonal: "Seasonal special",
    offerTitle: "Weekend dinner set",
    offerText: "Two mains, one dessert and two drinks for $49.",
    seeOffer: "See items",
    close: "Close",
    noResults: "No menu items found.",
    freshToday: "Freshly prepared and available today.",
    breakfastHours: "Served weekdays from 10:00 to 12:30.",
    spicyLabel: "Spicy",
    rating: "Rating",
    tableNumber: "Table number",
    pickupReady: "Ready in approximately 20–30 minutes.",
    restaurantSummary: "Open kitchen · seasonal menu · delivery",
    drinksUnavailableDelivery: "Drinks are available for pickup and dine-in only.",
    searchDelivery: "Search available delivery dishes..."
  },
  pl: {
    nav: ["Menu", "Dostawa", "Restauracja"],
    popular: "Popularne",
    food: "Jedzenie",
    drinks: "Napoje",
    search: "Szukaj dań, składników lub napojów...",
    all: "Wszystkie",
    filters: ["Wszystkie", "Popularne", "Wegetariańskie", "Pikantne", "Do $20"],
    infoTitle: "Informacje o lokalu",
    open: "Otwarte dzisiaj",
    address: "Adres",
    phone: "Telefon",
    delivery: "Dostawa",
    pickup: "Odbiór",
    dinein: "Na miejscu",
    eta: "25–40 min",
    minOrder: "Minimalne zamówienie",
    freeDelivery: "Darmowa dostawa od $45",
    favorites: "Ulubione",
    cart: "Koszyk",
    emptyFavorites: "Brak ulubionych pozycji.",
    emptyCart: "Koszyk jest pusty.",
    add: "Dodaj",
    added: "Dodano do koszyka",
    remove: "Usuń",
    subtotal: "Suma częściowa",
    fee: "Dostawa",
    total: "Razem",
    checkout: "Przejdź dalej",
    orderTitle: "Dane zamówienia",
    customerName: "Imię i nazwisko",
    customerPhone: "Numer telefonu",
    customerEmail: "Email",
    orderType: "Sposób odbioru",
    deliveryAddress: "Ulica i numer budynku",
    apartment: "Mieszkanie / domofon",
    city: "Miasto",
    postalCode: "Kod pocztowy",
    deliveryNotes: "Uwagi do dostawy",
    payment: "Metoda płatności",
    card: "Karta",
    cash: "Gotówka",
    placeOrder: "Złóż zamówienie demo",
    orderSuccess: "Zamówienie zostało złożone",
    quantity: "Ilość",
    details: "Szczegóły",
    ingredients: "Składniki",
    allergens: "Alergeny",
    preparation: "Przygotowanie",
    calories: "Kalorie",
    seasonal: "Oferta sezonowa",
    offerTitle: "Weekendowy zestaw kolacyjny",
    offerText: "Dwa dania główne, deser i dwa napoje za $49.",
    seeOffer: "Zobacz pozycje",
    close: "Zamknij",
    noResults: "Nie znaleziono pozycji.",
    freshToday: "Świeżo przygotowane i dostępne dzisiaj.",
    breakfastHours: "Serwowane w dni robocze od 10:00 do 12:30.",
    spicyLabel: "Pikantne",
    rating: "Ocena",
    tableNumber: "Numer stolika",
    pickupReady: "Gotowe za około 20–30 minut.",
    restaurantSummary: "Otwarta kuchnia · sezonowe menu · dostawa",
    drinksUnavailableDelivery: "Napoje są dostępne wyłącznie przy odbiorze i na miejscu.",
    searchDelivery: "Szukaj dań dostępnych z dostawą..."
  },
  uk: {
    nav: ["Меню", "Доставка", "Ресторан"],
    popular: "Популярне",
    food: "Страви",
    drinks: "Напої",
    search: "Пошук страв, інгредієнтів або напоїв...",
    all: "Усі",
    filters: ["Усі", "Популярні", "Вегетаріанські", "Гострі", "До $20"],
    infoTitle: "Інформація про заклад",
    open: "Відкрито сьогодні",
    address: "Адреса",
    phone: "Телефон",
    delivery: "Доставка",
    pickup: "Самовивіз",
    dinein: "У ресторані",
    eta: "25–40 хв",
    minOrder: "Мінімальне замовлення",
    freeDelivery: "Безкоштовна доставка від $45",
    favorites: "Улюблене",
    cart: "Кошик",
    emptyFavorites: "Поки немає улюблених позицій.",
    emptyCart: "Кошик порожній.",
    add: "Додати",
    added: "Додано до кошика",
    remove: "Видалити",
    subtotal: "Проміжна сума",
    fee: "Доставка",
    total: "Разом",
    checkout: "Оформити",
    orderTitle: "Дані замовлення",
    customerName: "Ім’я та прізвище",
    customerPhone: "Номер телефону",
    customerEmail: "Email",
    orderType: "Тип замовлення",
    deliveryAddress: "Вулиця та номер будинку",
    apartment: "Квартира / домофон",
    city: "Місто",
    postalCode: "Поштовий індекс",
    deliveryNotes: "Коментар до доставки",
    payment: "Спосіб оплати",
    card: "Картка",
    cash: "Готівка",
    placeOrder: "Оформити демо-замовлення",
    orderSuccess: "Замовлення оформлено",
    quantity: "Кількість",
    details: "Деталі",
    ingredients: "Інгредієнти",
    allergens: "Алергени",
    preparation: "Приготування",
    calories: "Калорії",
    seasonal: "Сезонна пропозиція",
    offerTitle: "Вечірній сет вихідного дня",
    offerText: "Дві основні страви, десерт і два напої за $49.",
    seeOffer: "Переглянути позиції",
    close: "Закрити",
    noResults: "Нічого не знайдено.",
    freshToday: "Свіжоприготоване та доступне сьогодні.",
    breakfastHours: "Подається у будні з 10:00 до 12:30.",
    spicyLabel: "Гостре",
    rating: "Оцінка",
    tableNumber: "Номер столика",
    pickupReady: "Буде готово приблизно за 20–30 хвилин.",
    restaurantSummary: "Відкрита кухня · сезонне меню · доставка",
    drinksUnavailableDelivery: "Напої доступні лише для самовивозу та замовлення в ресторані.",
    searchDelivery: "Пошук страв, доступних для доставки..."
  }
};

export const menuGroups = [
  { type: "food", category: "Breakfast", icon: Soup },
  { type: "food", category: "Starters", icon: Sparkles },
  { type: "food", category: "Main Course", icon: Utensils },
  { type: "food", category: "Fish", icon: Fish },
  { type: "food", category: "Pizza", icon: Pizza },
  { type: "food", category: "Desserts", icon: IceCreamBowl },
  { type: "drink", category: "Coffee", icon: Coffee },
  { type: "drink", category: "Tea", icon: GlassWater },
  { type: "drink", category: "Matcha", icon: GlassWater },
  { type: "drink", category: "Fresh Juices", icon: GlassWater },
  { type: "drink", category: "Refreshers", icon: GlassWater },
  { type: "drink", category: "Cocktails", icon: Wine },
  { type: "drink", category: "Wine", icon: Wine },
  { type: "drink", category: "Beer", icon: Beer },
  { type: "drink", category: "Spirits", icon: Wine }
];

export const items = [
  {
    id: 1, category: "Breakfast", type: "food", name: "Shrimp Pancakes",
    price: 16, rating: 4.9, weight: "350 g", prep: 18, calories: 510,
    popular: true, vegetarian: false, spicy: false,
    description: "Rice pancakes, shrimp, mango hollandaise and red caviar.",
    ingredients: ["rice pancakes", "shrimp", "mango", "egg yolk", "red caviar"],
    allergens: ["shellfish", "egg"],
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 2, category: "Breakfast", type: "food", name: "Miso Shakshuka",
    price: 14, rating: 4.8, weight: "320 g", prep: 16, calories: 460,
    popular: true, vegetarian: true, spicy: true,
    description: "Tomato base, eggs, edamame, cherry tomatoes and shishito peppers.",
    ingredients: ["tomato", "eggs", "edamame", "cherry tomatoes", "shishito"],
    allergens: ["egg", "soy"],
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 3, category: "Starters", type: "food", name: "Burrata & Charred Peach",
    price: 15, rating: 4.7, weight: "260 g", prep: 10, calories: 390,
    popular: false, vegetarian: true, spicy: false,
    description: "Creamy burrata, charred peach, basil oil and toasted almonds.",
    ingredients: ["burrata", "peach", "basil", "almonds"],
    allergens: ["milk", "nuts"],
    image: "https://images.unsplash.com/photo-1625943555419-56a2cb596640?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 4, category: "Main Course", type: "food", name: "Truffle Rigatoni",
    price: 22, rating: 4.9, weight: "420 g", prep: 22, calories: 720,
    popular: true, vegetarian: true, spicy: false,
    description: "Rigatoni, truffle cream, parmesan and crispy mushrooms.",
    ingredients: ["rigatoni", "truffle", "cream", "parmesan", "mushrooms"],
    allergens: ["gluten", "milk"],
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 5, category: "Main Course", type: "food", name: "Duck Breast & Plum",
    price: 27, rating: 4.8, weight: "410 g", prep: 28, calories: 690,
    popular: false, vegetarian: false, spicy: false,
    description: "Roasted duck, plum glaze, celeriac purée and baby carrots.",
    ingredients: ["duck", "plum", "celeriac", "carrot"],
    allergens: ["celery"],
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 6, category: "Fish", type: "food", name: "Salmon Tataki Rice",
    price: 24, rating: 4.8, weight: "390 g", prep: 20, calories: 610,
    popular: true, vegetarian: false, spicy: true,
    description: "Crispy rice, salmon tataki, fried egg, greens and furikake.",
    ingredients: ["salmon", "rice", "egg", "greens", "furikake"],
    allergens: ["fish", "egg", "sesame"],
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 7, category: "Pizza", type: "food", name: "Hot Honey Pepperoni",
    price: 19, rating: 4.9, weight: "520 g", prep: 18, calories: 880,
    popular: true, vegetarian: false, spicy: true,
    description: "Tomato, mozzarella, pepperoni, hot honey and oregano.",
    ingredients: ["dough", "tomato", "mozzarella", "pepperoni", "hot honey"],
    allergens: ["gluten", "milk"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 8, category: "Desserts", type: "food", name: "Pistachio Tiramisu",
    price: 10, rating: 4.9, weight: "180 g", prep: 6, calories: 440,
    popular: true, vegetarian: true, spicy: false,
    description: "Mascarpone, espresso, cocoa and pistachio cream.",
    ingredients: ["mascarpone", "espresso", "cocoa", "pistachio"],
    allergens: ["milk", "egg", "nuts", "gluten"],
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 9, category: "Coffee", type: "drink", name: "Flat White",
    price: 5, rating: 4.8, weight: "250 ml", prep: 5, calories: 120,
    popular: true, vegetarian: true, spicy: false,
    description: "Double espresso with silky steamed milk.",
    ingredients: ["espresso", "milk"],
    allergens: ["milk"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 10, category: "Tea", type: "drink", name: "Jasmine Pearl Tea",
    price: 5, rating: 4.6, weight: "400 ml", prep: 7, calories: 5,
    popular: false, vegetarian: true, spicy: false,
    description: "Delicate green tea with floral jasmine aroma.",
    ingredients: ["green tea", "jasmine"],
    allergens: [],
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 11, category: "Matcha", type: "drink", name: "Strawberry Matcha",
    price: 7, rating: 4.9, weight: "350 ml", prep: 6, calories: 180,
    popular: true, vegetarian: true, spicy: false,
    description: "Ceremonial matcha, strawberry purée and oat milk.",
    ingredients: ["matcha", "strawberry", "oat milk"],
    allergens: [],
    image: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 12, category: "Fresh Juices", type: "drink", name: "Orange Ginger Fresh",
    price: 7, rating: 4.7, weight: "350 ml", prep: 5, calories: 140,
    popular: false, vegetarian: true, spicy: false,
    description: "Fresh orange, ginger and a touch of lemon.",
    ingredients: ["orange", "ginger", "lemon"],
    allergens: [],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 13, category: "Refreshers", type: "drink", name: "Yuzu Basil Refresher",
    price: 8, rating: 4.8, weight: "400 ml", prep: 6, calories: 95,
    popular: true, vegetarian: true, spicy: false,
    description: "Yuzu, basil, sparkling water and citrus foam.",
    ingredients: ["yuzu", "basil", "sparkling water"],
    allergens: [],
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 14, category: "Cocktails", type: "drink", name: "Mango Chili Margarita",
    price: 13, rating: 4.9, weight: "180 ml", prep: 8, calories: 210,
    popular: true, vegetarian: true, spicy: true,
    description: "Tequila, mango, lime, chilli and smoked salt.",
    ingredients: ["tequila", "mango", "lime", "chilli"],
    allergens: [],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 15, category: "Wine", type: "drink", name: "Orange Wine",
    price: 11, rating: 4.7, weight: "150 ml", prep: 2, calories: 125,
    popular: false, vegetarian: true, spicy: false,
    description: "Dry, aromatic orange wine with stone-fruit notes.",
    ingredients: ["wine"],
    allergens: ["sulphites"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 16, category: "Beer", type: "drink", name: "Local Pale Ale",
    price: 8, rating: 4.6, weight: "500 ml", prep: 2, calories: 220,
    popular: false, vegetarian: true, spicy: false,
    description: "Citrusy local pale ale on tap.",
    ingredients: ["barley", "hops"],
    allergens: ["gluten"],
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85"
  },
  {
    id: 17, category: "Spirits", type: "drink", name: "Japanese Whisky",
    price: 15, rating: 4.8, weight: "50 ml", prep: 2, calories: 110,
    popular: false, vegetarian: true, spicy: false,
    description: "Smooth blended whisky with vanilla and oak notes.",
    ingredients: ["whisky"],
    allergens: [],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=900&q=85"
  }
];


export const categoryLabels = {
  en: {
    Popular: "Popular",
    Breakfast: "Breakfast",
    Starters: "Starters",
    "Main Course": "Main Course",
    Fish: "Fish",
    Pizza: "Pizza",
    Desserts: "Desserts",
    Coffee: "Coffee",
    Tea: "Tea",
    Matcha: "Matcha",
    "Fresh Juices": "Fresh Juices",
    Refreshers: "Refreshers",
    Cocktails: "Cocktails",
    Wine: "Wine",
    Beer: "Beer",
    Spirits: "Spirits"
  },
  pl: {
    Popular: "Popularne",
    Breakfast: "Śniadania",
    Starters: "Przystawki",
    "Main Course": "Dania główne",
    Fish: "Ryby",
    Pizza: "Pizza",
    Desserts: "Desery",
    Coffee: "Kawa",
    Tea: "Herbata",
    Matcha: "Matcha",
    "Fresh Juices": "Świeże soki",
    Refreshers: "Napoje orzeźwiające",
    Cocktails: "Koktajle",
    Wine: "Wino",
    Beer: "Piwo",
    Spirits: "Alkohole mocne"
  },
  uk: {
    Popular: "Популярне",
    Breakfast: "Сніданки",
    Starters: "Закуски",
    "Main Course": "Основні страви",
    Fish: "Риба",
    Pizza: "Піца",
    Desserts: "Десерти",
    Coffee: "Кава",
    Tea: "Чай",
    Matcha: "Матча",
    "Fresh Juices": "Фреші",
    Refreshers: "Освіжаючі напої",
    Cocktails: "Коктейлі",
    Wine: "Вино",
    Beer: "Пиво",
    Spirits: "Міцний алкоголь"
  }
};


export const itemTranslations = {
  en: {
    1: { name: "Shrimp Pancakes", description: "Rice pancakes, shrimp, mango hollandaise and red caviar.", ingredients: ["rice pancakes", "shrimp", "mango", "egg yolk", "red caviar"], allergens: ["shellfish", "egg"] },
    2: { name: "Miso Shakshuka", description: "Tomato base, eggs, edamame, cherry tomatoes and shishito peppers.", ingredients: ["tomato", "eggs", "edamame", "cherry tomatoes", "shishito"], allergens: ["egg", "soy"] },
    3: { name: "Burrata & Charred Peach", description: "Creamy burrata, charred peach, basil oil and toasted almonds.", ingredients: ["burrata", "peach", "basil", "almonds"], allergens: ["milk", "nuts"] },
    4: { name: "Truffle Rigatoni", description: "Rigatoni, truffle cream, parmesan and crispy mushrooms.", ingredients: ["rigatoni", "truffle", "cream", "parmesan", "mushrooms"], allergens: ["gluten", "milk"] },
    5: { name: "Duck Breast & Plum", description: "Roasted duck, plum glaze, celeriac purée and baby carrots.", ingredients: ["duck", "plum", "celeriac", "carrot"], allergens: ["celery"] },
    6: { name: "Salmon Tataki Rice", description: "Crispy rice, salmon tataki, fried egg, greens and furikake.", ingredients: ["salmon", "rice", "egg", "greens", "furikake"], allergens: ["fish", "egg", "sesame"] },
    7: { name: "Hot Honey Pepperoni", description: "Tomato, mozzarella, pepperoni, hot honey and oregano.", ingredients: ["dough", "tomato", "mozzarella", "pepperoni", "hot honey"], allergens: ["gluten", "milk"] },
    8: { name: "Pistachio Tiramisu", description: "Mascarpone, espresso, cocoa and pistachio cream.", ingredients: ["mascarpone", "espresso", "cocoa", "pistachio"], allergens: ["milk", "egg", "nuts", "gluten"] },
    9: { name: "Flat White", description: "Double espresso with silky steamed milk.", ingredients: ["espresso", "milk"], allergens: ["milk"] },
    10: { name: "Jasmine Pearl Tea", description: "Delicate green tea with a floral jasmine aroma.", ingredients: ["green tea", "jasmine"], allergens: [] },
    11: { name: "Strawberry Matcha", description: "Ceremonial matcha, strawberry purée and oat milk.", ingredients: ["matcha", "strawberry", "oat milk"], allergens: [] },
    12: { name: "Orange Ginger Fresh", description: "Fresh orange, ginger and a touch of lemon.", ingredients: ["orange", "ginger", "lemon"], allergens: [] },
    13: { name: "Yuzu Basil Refresher", description: "Yuzu, basil, sparkling water and citrus foam.", ingredients: ["yuzu", "basil", "sparkling water"], allergens: [] },
    14: { name: "Mango Chili Margarita", description: "Tequila, mango, lime, chilli and smoked salt.", ingredients: ["tequila", "mango", "lime", "chilli"], allergens: [] },
    15: { name: "Orange Wine", description: "Dry, aromatic orange wine with stone-fruit notes.", ingredients: ["wine"], allergens: ["sulphites"] },
    16: { name: "Local Pale Ale", description: "Citrusy local pale ale on tap.", ingredients: ["barley", "hops"], allergens: ["gluten"] },
    17: { name: "Japanese Whisky", description: "Smooth blended whisky with vanilla and oak notes.", ingredients: ["whisky"], allergens: [] }
  },
  pl: {
    1: { name: "Pancakes z krewetkami", description: "Ryżowe pancakes, krewetki, holenderski sos mango i czerwona ikra.", ingredients: ["pancakes ryżowe", "krewetki", "mango", "żółtko", "czerwona ikra"], allergens: ["skorupiaki", "jajka"] },
    2: { name: "Szakszuka miso", description: "Sos pomidorowy, jajka, edamame, pomidorki koktajlowe i papryczki shishito.", ingredients: ["pomidory", "jajka", "edamame", "pomidorki koktajlowe", "shishito"], allergens: ["jajka", "soja"] },
    3: { name: "Burrata z grillowaną brzoskwinią", description: "Kremowa burrata, grillowana brzoskwinia, olej bazyliowy i prażone migdały.", ingredients: ["burrata", "brzoskwinia", "bazylia", "migdały"], allergens: ["mleko", "orzechy"] },
    4: { name: "Rigatoni truflowe", description: "Rigatoni, krem truflowy, parmezan i chrupiące grzyby.", ingredients: ["rigatoni", "trufla", "śmietanka", "parmezan", "grzyby"], allergens: ["gluten", "mleko"] },
    5: { name: "Pierś z kaczki i śliwka", description: "Pieczona kaczka, glazura śliwkowa, purée z selera i młode marchewki.", ingredients: ["kaczka", "śliwka", "seler", "marchew"], allergens: ["seler"] },
    6: { name: "Ryż z tataki z łososia", description: "Chrupiący ryż, tataki z łososia, jajko sadzone, zielenina i furikake.", ingredients: ["łosoś", "ryż", "jajko", "zielenina", "furikake"], allergens: ["ryby", "jajka", "sezam"] },
    7: { name: "Pepperoni z pikantnym miodem", description: "Pomidory, mozzarella, pepperoni, pikantny miód i oregano.", ingredients: ["ciasto", "pomidory", "mozzarella", "pepperoni", "pikantny miód"], allergens: ["gluten", "mleko"] },
    8: { name: "Tiramisu pistacjowe", description: "Mascarpone, espresso, kakao i krem pistacjowy.", ingredients: ["mascarpone", "espresso", "kakao", "pistacje"], allergens: ["mleko", "jajka", "orzechy", "gluten"] },
    9: { name: "Flat white", description: "Podwójne espresso z aksamitnie spienionym mlekiem.", ingredients: ["espresso", "mleko"], allergens: ["mleko"] },
    10: { name: "Herbata jaśminowa Pearl", description: "Delikatna zielona herbata o kwiatowym aromacie jaśminu.", ingredients: ["zielona herbata", "jaśmin"], allergens: [] },
    11: { name: "Matcha truskawkowa", description: "Ceremonialna matcha, purée truskawkowe i mleko owsiane.", ingredients: ["matcha", "truskawka", "mleko owsiane"], allergens: [] },
    12: { name: "Fresh pomarańcza–imbir", description: "Świeża pomarańcza, imbir i odrobina cytryny.", ingredients: ["pomarańcza", "imbir", "cytryna"], allergens: [] },
    13: { name: "Yuzu–bazylia refresher", description: "Yuzu, bazylia, woda gazowana i cytrusowa pianka.", ingredients: ["yuzu", "bazylia", "woda gazowana"], allergens: [] },
    14: { name: "Margarita mango–chilli", description: "Tequila, mango, limonka, chilli i wędzona sól.", ingredients: ["tequila", "mango", "limonka", "chilli"], allergens: [] },
    15: { name: "Wino pomarańczowe", description: "Wytrawne, aromatyczne wino pomarańczowe z nutami owoców pestkowych.", ingredients: ["wino"], allergens: ["siarczyny"] },
    16: { name: "Lokalne pale ale", description: "Cytrusowe lokalne pale ale z kranu.", ingredients: ["jęczmień", "chmiel"], allergens: ["gluten"] },
    17: { name: "Japońska whisky", description: "Łagodna whisky blended z nutami wanilii i dębu.", ingredients: ["whisky"], allergens: [] }
  },
  uk: {
    1: { name: "Панкейки з креветками", description: "Рисові панкейки, креветки, манговий голландез і червона ікра.", ingredients: ["рисові панкейки", "креветки", "манго", "яєчний жовток", "червона ікра"], allergens: ["ракоподібні", "яйця"] },
    2: { name: "Шакшука місо", description: "Томатна основа, яйця, едамаме, помідори чері та перець шишіто.", ingredients: ["томати", "яйця", "едамаме", "помідори чері", "шишіто"], allergens: ["яйця", "соя"] },
    3: { name: "Бурата з обпаленою персиковою часточкою", description: "Кремова бурата, обпалений персик, базилікова олія та підсмажений мигдаль.", ingredients: ["бурата", "персик", "базилік", "мигдаль"], allergens: ["молоко", "горіхи"] },
    4: { name: "Трюфельні ригатоні", description: "Ригатоні, трюфельний крем, пармезан і хрусткі гриби.", ingredients: ["риґатоні", "трюфель", "вершки", "пармезан", "гриби"], allergens: ["глютен", "молоко"] },
    5: { name: "Качина грудка зі сливою", description: "Запечена качка, сливова глазур, пюре із селери та молода морква.", ingredients: ["качка", "слива", "селера", "морква"], allergens: ["селера"] },
    6: { name: "Рис із татакі з лосося", description: "Хрусткий рис, татакі з лосося, смажене яйце, зелень і фурікаке.", ingredients: ["лосось", "рис", "яйце", "зелень", "фурікаке"], allergens: ["риба", "яйця", "кунжут"] },
    7: { name: "Пепероні з гострим медом", description: "Томати, моцарела, пепероні, гострий мед та орегано.", ingredients: ["тісто", "томати", "моцарела", "пепероні", "гострий мед"], allergens: ["глютен", "молоко"] },
    8: { name: "Фісташковий тірамісу", description: "Маскарпоне, еспресо, какао та фісташковий крем.", ingredients: ["маскарпоне", "еспресо", "какао", "фісташка"], allergens: ["молоко", "яйця", "горіхи", "глютен"] },
    9: { name: "Флет-вайт", description: "Подвійний еспресо з ніжним спіненим молоком.", ingredients: ["еспресо", "молоко"], allergens: ["молоко"] },
    10: { name: "Жасминовий чай Pearl", description: "Ніжний зелений чай із квітковим ароматом жасмину.", ingredients: ["зелений чай", "жасмин"], allergens: [] },
    11: { name: "Полунична матча", description: "Церемоніальна матча, полуничне пюре та вівсяне молоко.", ingredients: ["матча", "полуниця", "вівсяне молоко"], allergens: [] },
    12: { name: "Апельсиново-імбирний фреш", description: "Свіжий апельсин, імбир і трохи лимона.", ingredients: ["апельсин", "імбир", "лимон"], allergens: [] },
    13: { name: "Рефрешер юзу–базилік", description: "Юзу, базилік, газована вода та цитрусова піна.", ingredients: ["юзу", "базилік", "газована вода"], allergens: [] },
    14: { name: "Маргарита манго–чилі", description: "Текіла, манго, лайм, чилі та копчена сіль.", ingredients: ["текіла", "манго", "лайм", "чилі"], allergens: [] },
    15: { name: "Помаранчеве вино", description: "Сухе ароматне помаранчеве вино з нотами кісточкових фруктів.", ingredients: ["вино"], allergens: ["сульфіти"] },
    16: { name: "Локальний pale ale", description: "Цитрусовий локальний pale ale на розлив.", ingredients: ["ячмінь", "хміль"], allergens: ["глютен"] },
    17: { name: "Японський віскі", description: "М’який купажований віскі з нотами ванілі та дуба.", ingredients: ["віскі"], allergens: [] }
  }
};